### ISSUE TITLE
Starting with the basics

### ISSUE THREAD

**Issue by GroophyLifefor** [exercism/batch-test-runner#1]
Ok, for better or worse, we have written the Hello World exercise and here we are going to start parallel work for the test runner, but even if I skim through the readme, I get stuck when everything is given all at once and I say, Hey Murat (my real name) how are you going to start now?

So can we start from the basics and give me a basic idea of how to get started?
I'm not very professional especially on how to integrate Docker.

Help wanted from: @ErikSchierboom

**Comment by ErikSchierboom** [comment]
Sorry, this is a slightly broad question, so I don't know what specifically would be useful. But this is the general idea:

- The goal of the test runner repo is to produce a Docker image that we use to verify that a student's solution passes all the tests
- The `Dockerfile` in the test runner repo sets-up the "environment" to be able to run the tests, so everything that is needed to run the tests needs to be installed in the Dockerfile
- The Docker image will be run with the student's solution mounted into it. Its location will be passed in as an argument (see https://exercism.org/docs/building/tooling/test-runners/interface)
- The test runner needs to then produce a `results.json` file that is a summary of the test results (did the tests pass/fail/error?). See https://exercism.org/docs/building/tooling/test-runners/interface for a description of its format

The https://github.com/exercism/batch-test-runner/ repo has some basic files setup to help you get started. Did you check its README.md?

The first steps would be to try and familiarize yourself with the files in the batch test runner repo. Are you on Windows, macOS or *nix?

**Comment by GroophyLifefor** [comment]
I'm using Windows, and I'm currently trying adapt readme to code at initialize branch.
